# Generated by Django 3.2.4 on 2021-06-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("right", models.IntegerField(blank=True, null=True)),
                ("left", models.IntegerField(blank=True, null=True)),
                ("parent_name", models.CharField(default="NULL", max_length=100)),
            ],
            options={
                "db_table": "application_category",
                "ordering": ("left",),
            },
        ),
    ]
